apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ .Chart.Name }}
    spec:
      containers:
      - name: fast-neural-style
        resources:
          requests:
            cpu: "{{ .Values.cpu.requests }}"
            memory: "{{ .Values.memory.requests }}"
            alpha.kubernetes.io/nvidia-gpu: 1
          limits:
            cpu: "{{ .Values.cpu.limits }}"
            memory: "{{ .Values.memory.limits }}"
        image: "{{ printf "%s:%s" .Values.image.Name .Values.image.Tag }}"
        ports:
        - containerPort: 8888
          name: jupyter
        - containerPort: 6006
          name: tensor-board 
        - containerPort: 4200
          name: shellinabox
        volumeMounts:
        - name: notebooks
          mountPath: "/notebooks/{{ .Chart.Name }}"
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/lib/nvidia/lib64
          name: lib64
        - mountPath: /usr/lib/nvidia/lib
          name: lib
        - mountPath: /usr/local/cuda/extras/CUPTI/lib64
          name: capti
      volumes:
      - name: notebooks
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: "{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 24 }}"
        {{- else }}
        emptyDir: {}
        {{- end }}
      - hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.39/bin
        name: bin
      - hostPath: 
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.39/lib64
        name: lib
      - hostPath:
          path: /usr/local/cuda/extras/CUPTI/lib64
        name: capti
